//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maxter_Management.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Address
    {
        public string street_name { get; set; }
        public string street_type { get; set; }
        public string house_nr { get; set; }
        public string block { get; set; }
        public string entrance { get; set; }
        public string floor { get; set; }
        public string door { get; set; }
        public string city { get; set; }
        public string postcode { get; set; }
        public string country { get; set; }
        public string district { get; set; }
        public string Address_ID { get; set; }

        public string ToListView()
        {
            return $"{country}, {postcode} {city}, {street_name} {street_type} {house_nr}";
        }
    }
}