//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maxter_Management.Models
{
    using System;
    using System.Collections.Generic;

    public partial class EAN
    {
        private int _eanId;
        private string _ean1;
        private int? _quantity;
        private string _sku;

        public int EAN_id
        {
            get => _eanId;
            private set => _eanId = value;
        }

        public string EAN1
        {
            get => _ean1;
            set => _ean1 = value;
        }

        public Nullable<int> Quantity
        {
            get => _quantity;
            set => _quantity = value;
        }

        public string SKU
        {
            get => _sku;
            set => _sku = value;
        }

        public virtual Product Product { get; set; }

        public EAN() { }

        public EAN(string eAN1, int? quantity, string sKU)
        {
            EAN1 = eAN1;
            Quantity = quantity;
            SKU = sKU;

            using (MaxterDBEntities context = new MaxterDBEntities())
            {
                int max = 0;
                foreach (EAN item in context.EANs)
                {
                    if (item.EAN_id > max)
                    {
                        max = item.EAN_id;
                    }
                }

                EAN_id = max + 1;
            }
        }
    }
}