//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maxter_Management.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Order_detail
    {
        private int _orderDetailId;
        private int _orderId;
        private string _sku;
        private decimal? _itemPrice;
        private int _orderedQuantity;
        private Order _order;
        private Product _product;

        public int Order_Detail_id
        {
            get => _orderDetailId;
            set => _orderDetailId = value;
        }

        public int Order_id
        {
            get => _orderId;
            set => _orderId = value;
        }

        public string SKU
        {
            get => _sku;
            set => _sku = value;
        }

        public Nullable<decimal> Item_Price
        {
            get => _itemPrice;
            set => _itemPrice = value;
        }

        public int Ordered_Quantity
        {
            get => _orderedQuantity;
            set => _orderedQuantity = value;
        }

        public virtual Order Order
        {
            get => _order;
            set => _order = value;
        }

        public virtual Product Product
        {
            get => _product;
            set => _product = value;
        }

        public Order_detail(int order_id, string sKU, decimal? item_Price, int ordered_Quantity)
        {
            Order_id = order_id;
            SKU = sKU;
            Item_Price = item_Price;
            Ordered_Quantity = ordered_Quantity;

            using (MaxterDBEntities context = new MaxterDBEntities())
            {
                int max = 0;
                foreach (Order_detail item in context.Order_detail)
                {
                    if (item.Order_Detail_id > max)
                    {
                        max = item.Order_Detail_id;
                    }
                }

                Order_Detail_id = max + 1;
            }
        }

        public Order_detail()
        {

        }
    }
}
