//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maxter_Management.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Order
    {
        private int _orderId;
        private int _partnerId;
        private DateTime _orderDate;
        private DateTime _requiredDate;
        private DateTime? _shippedDate;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_detail = new HashSet<Order_detail>();
        }

        public int Order_id
        {
            get => _orderId;
            set => _orderId = value;
        }

        public int Partner_id
        {
            get => _partnerId;
            set => _partnerId = value;
        }

        public System.DateTime Order_date
        {
            get => _orderDate;
            set => _orderDate = value;
        }

        public System.DateTime Required_date
        {
            get => _requiredDate;
            set => _requiredDate = value;
        }

        public Nullable<System.DateTime> Shipped_date
        {
            get => _shippedDate;
            set => _shippedDate = value;
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_detail> Order_detail { get; set; }
        public virtual Partner Partner { get; set; }

        public Order(int partner_id)
        {
            Partner_id = partner_id;

            using (MaxterDBEntities context = new MaxterDBEntities())
            {
                int max = 0;
                foreach (Order item in context.Orders)
                {
                    if (item.Order_id > max)
                    {
                        max = item.Order_id;
                    }
                }

                Order_id = max + 1;
            }
        }
    }
}
