//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maxter_Management.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Partner
    {
        private string _tin;
        private int _partnerId;
        private string _name;
        private string _invoiceAddress;
        private string _shippingAddress;
        private byte? _priceCategory;
        private string _email;
        private string _telephone;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage",
            "CA2214:DoNotCallOverridableMethodsInConstructors")]


        public string TIN
        {
            get => _tin;
            private set => _tin = value;
        }

        public int Partner_id
        {
            get => _partnerId;
            set => _partnerId = value;
        }

        public string Name
        {
            get => _name;
            set => _name = value;
        }

        public string Invoice_Address
        {
            get => _invoiceAddress;
            set => _invoiceAddress = value;
        }

        public string Shipping_Address
        {
            get => _shippingAddress;
            set => _shippingAddress = value;
        }

        public Nullable<byte> Price_Category
        {
            get => _priceCategory;
            set => _priceCategory = value;
        }

        public string Email
        {
            get => _email;
            set => _email = value;
        }

        public string Telephone
        {
            get => _telephone;
            set => _telephone = value;
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }

        public Partner()
        {
            this.Orders = new HashSet<Order>();
        }

        public Partner(string tIN, string name, string invoice_Address, string shipping_Address, byte? price_Category, string email, string telephone)
        {
            TIN = tIN;
            Name = name;
            Invoice_Address = invoice_Address;
            Shipping_Address = shipping_Address;
            Price_Category = price_Category;
            Email = email;
            Telephone = telephone;

            using (MaxterDBEntities context = new MaxterDBEntities())
            {
                int max = 0;
                foreach (Partner item in context.Partners)
                {
                    if (item.Partner_id > max)
                    {
                        max = item.Partner_id;
                    }
                }

                Partner_id = max + 1;
            }

            this.Orders = new HashSet<Order>();
        }
    }
}
