//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows.Forms;

namespace Maxter_Management.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.EANs = new HashSet<EAN>();
            this.Order_detail = new HashSet<Order_detail>();
            this.Prices = new HashSet<Price>();
        }

        private string sku;

        public string SKU
        {
            get { return sku; }
            set
            {
                if (value.Trim().Length > 0)
                {
                    sku = value;
                }
                else
                {
                    throw new ArgumentException("SKU can not be empty!");
                }
            }
        }

        public string Description { get; set; }
        public string VTSZ { get; set; }
        public Nullable<short> Stock_Quantity { get; set; }
        public Nullable<short> Min_Stock_Quantity { get; set; }
        public string PU { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EAN> EANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_detail> Order_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Price> Prices { get; set; }
    }
}
