//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows.Forms;

namespace Maxter_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        private int id;
        private string first_name;
        private string last_name;
        private string username;
        private string password;
        private string access;

        public int Id { get; set; }

        public string First_name
        {
            get { return first_name; }

            set
            {
                if (value.Trim().Length > 0 && value.Trim().Length < 16)
                {
                    first_name = value;
                }
                else
                {
                    MessageBox.Show("First name must be 1-15 characters long!");
                }
            }
        }

        public string Last_name 
        {
            get { return last_name; }

            set
            {
                if (value.Trim().Length > 0 && value.Trim().Length < 16)
                {
                    last_name = value;
                }
                else
                {
                    MessageBox.Show("Last name must be 1-15 characters long!");
                }
            }
        }

        public string Username
        {
            get { return username; }

            set
            {
                if (value.Trim().Length > 0 && value.Trim().Length <= 8)
                {
                    username = value;
                }
                else
                {
                    MessageBox.Show("Username must be 1-8 characters long!");
                }
            }
        }

        public string Password
        {
            get { return password; }

            set { password = value; }
        }

        public string Access
        {
            get
            { return access; }

            set
            {
                if (value.Trim().Length > 0)
                {
                    access = value;
                }
                else
                {
                    MessageBox.Show("Access must not be empty!");
                }
            }
        }

        public User()
        {
        }

        public User(string first_name, string last_name, string username, string password, string access)
        {
            First_name = first_name;
            Last_name = last_name;
            Username = username;
            Password = password;
            Access = access;
        }

        public User(string first_name, string last_name, string username, string access)
        {
            First_name = first_name;
            Last_name = last_name;
            Username = username;
            Access = access;
        }

        public override string ToString()
        {
            return $"{Id} - {Username}";
        }
    }
}
