//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maxter_Management.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DynamicResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DynamicResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Maxter_Management.Resources.DynamicResources", typeof(DynamicResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AdminSettingsFrm_button1_Click_Are_you_sure_ {
            get {
                return ResourceManager.GetString("AdminSettingsFrm_button1_Click_Are_you_sure_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string AdminSettingsFrm_button1_Click_Confirmation {
            get {
                return ResourceManager.GetString("AdminSettingsFrm_button1_Click_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figyelmeztetés.
        /// </summary>
        internal static string AdminSettingsFrm_button1_Click_Figyelmeztetés {
            get {
                return ResourceManager.GetString("AdminSettingsFrm_button1_Click_Figyelmeztetés", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jelszó hosszúságának 6 és 24 karakter között kell lennie!.
        /// </summary>
        internal static string AdminSettingsFrm_button1_Click_Password_Length {
            get {
                return ResourceManager.GetString("AdminSettingsFrm_button1_Click_Password_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill every field!.
        /// </summary>
        internal static string AdminSettingsFrm_button1_Click_Please_fill_every_field_ {
            get {
                return ResourceManager.GetString("AdminSettingsFrm_button1_Click_Please_fill_every_field_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string AdminSettingsFrm_button1_Click_Warning {
            get {
                return ResourceManager.GetString("AdminSettingsFrm_button1_Click_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected user?.
        /// </summary>
        internal static string AdminSettingsFrm_button3_Click_Delete_selected_user_ {
            get {
                return ResourceManager.GetString("AdminSettingsFrm_button3_Click_Delete_selected_user_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string AdminSettingsFrm_checkBox5_CheckedChanged_Cancel {
            get {
                return ResourceManager.GetString("AdminSettingsFrm_checkBox5_CheckedChanged_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel editing?.
        /// </summary>
        internal static string AdminSettingsFrm_checkBox5_CheckedChanged_Cancel_editing_ {
            get {
                return ResourceManager.GetString("AdminSettingsFrm_checkBox5_CheckedChanged_Cancel_editing_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string MenuFunctions_Billing_Click_Client {
            get {
                return ResourceManager.GetString("MenuFunctions_Billing_Click_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string MenuFunctions_Billing_Click_Close {
            get {
                return ResourceManager.GetString("MenuFunctions_Billing_Click_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create invoice.
        /// </summary>
        internal static string MenuFunctions_Billing_Click_Create_invoice {
            get {
                return ResourceManager.GetString("MenuFunctions_Billing_Click_Create_invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of creation.
        /// </summary>
        internal static string MenuFunctions_Billing_Click_Date {
            get {
                return ResourceManager.GetString("MenuFunctions_Billing_Click_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download invoices.
        /// </summary>
        internal static string MenuFunctions_Billing_Click_Download_invoices {
            get {
                return ResourceManager.GetString("MenuFunctions_Billing_Click_Download_invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string MenuFunctions_Billing_Click_Finish {
            get {
                return ResourceManager.GetString("MenuFunctions_Billing_Click_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice ID.
        /// </summary>
        internal static string MenuFunctions_Billing_Click_Invoice_Id {
            get {
                return ResourceManager.GetString("MenuFunctions_Billing_Click_Invoice_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load invoices.
        /// </summary>
        internal static string MenuFunctions_Billing_Click_Load_invoices {
            get {
                return ResourceManager.GetString("MenuFunctions_Billing_Click_Load_invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string MenuFunctions_CreateOrder_Description {
            get {
                return ResourceManager.GetString("MenuFunctions_CreateOrder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string MenuFunctions_CreateOrder_Price {
            get {
                return ResourceManager.GetString("MenuFunctions_CreateOrder_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PU.
        /// </summary>
        internal static string MenuFunctions_CreateOrder_PU {
            get {
                return ResourceManager.GetString("MenuFunctions_CreateOrder_PU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string MenuFunctions_CreateOrder_Qty {
            get {
                return ResourceManager.GetString("MenuFunctions_CreateOrder_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU.
        /// </summary>
        internal static string MenuFunctions_CreateOrder_SKU {
            get {
                return ResourceManager.GetString("MenuFunctions_CreateOrder_SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices are not downloaded. Please download invoices first..
        /// </summary>
        internal static string MenuFunctions_LoadInvoices_Click_Invoices_are_not_downloaded__Please_download_invoices_first_ {
            get {
                return ResourceManager.GetString("MenuFunctions_LoadInvoices_Click_Invoices_are_not_downloaded__Please_download_inv" +
                        "oices_first_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string MenuFunctions_LoadInvoices_Click_Warning {
            get {
                return ResourceManager.GetString("MenuFunctions_LoadInvoices_Click_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MenuFunctions_Login_Error {
            get {
                return ResourceManager.GetString("MenuFunctions_Login_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed login!.
        /// </summary>
        internal static string MenuFunctions_Login_Failed_login_ {
            get {
                return ResourceManager.GetString("MenuFunctions_Login_Failed_login_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin settings.
        /// </summary>
        internal static string MenuFunctions_MainMenu_Admin {
            get {
                return ResourceManager.GetString("MenuFunctions_MainMenu_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        internal static string MenuFunctions_MainMenu_Billing {
            get {
                return ResourceManager.GetString("MenuFunctions_MainMenu_Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string MenuFunctions_MainMenu_Data {
            get {
                return ResourceManager.GetString("MenuFunctions_MainMenu_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MenuFunctions_MainMenu_Exit {
            get {
                return ResourceManager.GetString("MenuFunctions_MainMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string MenuFunctions_MainMenu_File {
            get {
                return ResourceManager.GetString("MenuFunctions_MainMenu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billingo API Connection.
        /// </summary>
        internal static string MenuFunctions_MainMenu_InvoiceSettings {
            get {
                return ResourceManager.GetString("MenuFunctions_MainMenu_InvoiceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        internal static string MenuFunctions_MainMenu_Lang {
            get {
                return ResourceManager.GetString("MenuFunctions_MainMenu_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string MenuFunctions_MainMenu_Orders {
            get {
                return ResourceManager.GetString("MenuFunctions_MainMenu_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partners.
        /// </summary>
        internal static string MenuFunctions_MainMenu_Partners {
            get {
                return ResourceManager.GetString("MenuFunctions_MainMenu_Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string MenuFunctions_MainMenu_Pass {
            get {
                return ResourceManager.GetString("MenuFunctions_MainMenu_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string MenuFunctions_MainMenu_Products {
            get {
                return ResourceManager.GetString("MenuFunctions_MainMenu_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID: .
        /// </summary>
        internal static string MenuFunctions_ModifyOrder_Click_Order_ID__ {
            get {
                return ResourceManager.GetString("MenuFunctions_ModifyOrder_Click_Order_ID__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner: .
        /// </summary>
        internal static string MenuFunctions_ModifyOrder_Click_Partner__ {
            get {
                return ResourceManager.GetString("MenuFunctions_ModifyOrder_Click_Partner__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested amount exceeds current stock! Avaiable stock: {0}.
        /// </summary>
        internal static string MenuFunctions_OrderDgv_CellEndEdit_Requested_amount_exceeds_current_stock__Avaiable_stock___0_ {
            get {
                return ResourceManager.GetString("MenuFunctions_OrderDgv_CellEndEdit_Requested_amount_exceeds_current_stock__Avaiab" +
                        "le_stock___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string MenuFunctions_OrderDgv_Desc_ {
            get {
                return ResourceManager.GetString("MenuFunctions_OrderDgv_Desc_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected item?.
        /// </summary>
        internal static string MenuFunctions_OrderDgv_KeyDown_Delete_selected_item_ {
            get {
                return ResourceManager.GetString("MenuFunctions_OrderDgv_KeyDown_Delete_selected_item_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string MenuFunctions_OrderDgv_Price_ {
            get {
                return ResourceManager.GetString("MenuFunctions_OrderDgv_Price_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PU.
        /// </summary>
        internal static string MenuFunctions_OrderDgv_Pu_ {
            get {
                return ResourceManager.GetString("MenuFunctions_OrderDgv_Pu_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string MenuFunctions_OrderDgv_Qty_ {
            get {
                return ResourceManager.GetString("MenuFunctions_OrderDgv_Qty_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU.
        /// </summary>
        internal static string MenuFunctions_OrderDgv_Sku_ {
            get {
                return ResourceManager.GetString("MenuFunctions_OrderDgv_Sku_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not shipped.
        /// </summary>
        internal static string MenuFunctions_OrderMenu_NotShipped {
            get {
                return ResourceManager.GetString("MenuFunctions_OrderMenu_NotShipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        internal static string MenuFunctions_OrderMenu_OderDate {
            get {
                return ResourceManager.GetString("MenuFunctions_OrderMenu_OderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order details.
        /// </summary>
        internal static string MenuFunctions_OrderMenu_OrderDetail {
            get {
                return ResourceManager.GetString("MenuFunctions_OrderMenu_OrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        internal static string MenuFunctions_OrderMenu_OrderID {
            get {
                return ResourceManager.GetString("MenuFunctions_OrderMenu_OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner.
        /// </summary>
        internal static string MenuFunctions_OrderMenu_Partner {
            get {
                return ResourceManager.GetString("MenuFunctions_OrderMenu_Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner ID.
        /// </summary>
        internal static string MenuFunctions_OrderMenu_PartnerID {
            get {
                return ResourceManager.GetString("MenuFunctions_OrderMenu_PartnerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Date.
        /// </summary>
        internal static string MenuFunctions_OrderMenu_ReqDate {
            get {
                return ResourceManager.GetString("MenuFunctions_OrderMenu_ReqDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped Date.
        /// </summary>
        internal static string MenuFunctions_OrderMenu_ShipDate {
            get {
                return ResourceManager.GetString("MenuFunctions_OrderMenu_ShipDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create order.
        /// </summary>
        internal static string MenuFunctions_Orders_Click_Create_order {
            get {
                return ResourceManager.GetString("MenuFunctions_Orders_Click_Create_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill stock.
        /// </summary>
        internal static string MenuFunctions_Orders_Click_Fill_stock {
            get {
                return ResourceManager.GetString("MenuFunctions_Orders_Click_Fill_stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as shipped.
        /// </summary>
        internal static string MenuFunctions_Orders_Click_Mark_as_shipped {
            get {
                return ResourceManager.GetString("MenuFunctions_Orders_Click_Mark_as_shipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify order.
        /// </summary>
        internal static string MenuFunctions_Orders_Click_Modify_order {
            get {
                return ResourceManager.GetString("MenuFunctions_Orders_Click_Modify_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove order.
        /// </summary>
        internal static string MenuFunctions_Orders_Click_Remove_order {
            get {
                return ResourceManager.GetString("MenuFunctions_Orders_Click_Remove_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create partner.
        /// </summary>
        internal static string MenuFunctions_PartnerMenu_Create_partner {
            get {
                return ResourceManager.GetString("MenuFunctions_PartnerMenu_Create_partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string MenuFunctions_PartnerMenu_Email {
            get {
                return ResourceManager.GetString("MenuFunctions_PartnerMenu_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Address.
        /// </summary>
        internal static string MenuFunctions_PartnerMenu_InvoiceAddress {
            get {
                return ResourceManager.GetString("MenuFunctions_PartnerMenu_InvoiceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify partner.
        /// </summary>
        internal static string MenuFunctions_PartnerMenu_Modify_partner {
            get {
                return ResourceManager.GetString("MenuFunctions_PartnerMenu_Modify_partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string MenuFunctions_PartnerMenu_Name {
            get {
                return ResourceManager.GetString("MenuFunctions_PartnerMenu_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string MenuFunctions_PartnerMenu_Orders {
            get {
                return ResourceManager.GetString("MenuFunctions_PartnerMenu_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner ID.
        /// </summary>
        internal static string MenuFunctions_PartnerMenu_PartnerId {
            get {
                return ResourceManager.GetString("MenuFunctions_PartnerMenu_PartnerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Category.
        /// </summary>
        internal static string MenuFunctions_PartnerMenu_PriceCategory {
            get {
                return ResourceManager.GetString("MenuFunctions_PartnerMenu_PriceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove partner.
        /// </summary>
        internal static string MenuFunctions_PartnerMenu_Remove_partner {
            get {
                return ResourceManager.GetString("MenuFunctions_PartnerMenu_Remove_partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address.
        /// </summary>
        internal static string MenuFunctions_PartnerMenu_ShippingAddress {
            get {
                return ResourceManager.GetString("MenuFunctions_PartnerMenu_ShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Number.
        /// </summary>
        internal static string MenuFunctions_PartnerMenu_Telephone {
            get {
                return ResourceManager.GetString("MenuFunctions_PartnerMenu_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIN.
        /// </summary>
        internal static string MenuFunctions_PartnerMenu_TIN {
            get {
                return ResourceManager.GetString("MenuFunctions_PartnerMenu_TIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add EAN.
        /// </summary>
        internal static string MenuFunctions_ProductMenu_Add_EAN {
            get {
                return ResourceManager.GetString("MenuFunctions_ProductMenu_Add_EAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Price.
        /// </summary>
        internal static string MenuFunctions_ProductMenu_Add_Price {
            get {
                return ResourceManager.GetString("MenuFunctions_ProductMenu_Add_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string MenuFunctions_ProductMenu_Category {
            get {
                return ResourceManager.GetString("MenuFunctions_ProductMenu_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new record.
        /// </summary>
        internal static string MenuFunctions_ProductMenu_Create_new_record {
            get {
                return ResourceManager.GetString("MenuFunctions_ProductMenu_Create_new_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTN.
        /// </summary>
        internal static string MenuFunctions_ProductMenu_CTN {
            get {
                return ResourceManager.GetString("MenuFunctions_ProductMenu_CTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string MenuFunctions_ProductMenu_Desc {
            get {
                return ResourceManager.GetString("MenuFunctions_ProductMenu_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAN.
        /// </summary>
        internal static string MenuFunctions_ProductMenu_EAN {
            get {
                return ResourceManager.GetString("MenuFunctions_ProductMenu_EAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAN count.
        /// </summary>
        internal static string MenuFunctions_ProductMenu_EanCount {
            get {
                return ResourceManager.GetString("MenuFunctions_ProductMenu_EanCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EANs.
        /// </summary>
        internal static string MenuFunctions_ProductMenu_EANs {
            get {
                return ResourceManager.GetString("MenuFunctions_ProductMenu_EANs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string MenuFunctions_ProductMenu_ID {
            get {
                return ResourceManager.GetString("MenuFunctions_ProductMenu_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. Stock Qty..
        /// </summary>
        internal static string MenuFunctions_ProductMenu_Min {
            get {
                return ResourceManager.GetString("MenuFunctions_ProductMenu_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify EAN.
        /// </summary>
        internal static string MenuFunctions_ProductMenu_Modify_EAN {
            get {
                return ResourceManager.GetString("MenuFunctions_ProductMenu_Modify_EAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Price.
        /// </summary>
        internal static string MenuFunctions_ProductMenu_Modify_Price {
            get {
                return ResourceManager.GetString("MenuFunctions_ProductMenu_Modify_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify record.
        /// </summary>
        internal static string MenuFunctions_ProductMenu_Modify_record {
            get {
                return ResourceManager.GetString("MenuFunctions_ProductMenu_Modify_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        internal static string MenuFunctions_ProductMenu_Number {
            get {
                return ResourceManager.GetString("MenuFunctions_ProductMenu_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders including item.
        /// </summary>
        internal static string MenuFunctions_ProductMenu_Orders_including_item {
            get {
                return ResourceManager.GetString("MenuFunctions_ProductMenu_Orders_including_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders count.
        /// </summary>
        internal static string MenuFunctions_ProductMenu_OrdersCount {
            get {
                return ResourceManager.GetString("MenuFunctions_ProductMenu_OrdersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prices.
        /// </summary>
        internal static string MenuFunctions_ProductMenu_Prices {
            get {
                return ResourceManager.GetString("MenuFunctions_ProductMenu_Prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prices count.
        /// </summary>
        internal static string MenuFunctions_ProductMenu_PricesCount {
            get {
                return ResourceManager.GetString("MenuFunctions_ProductMenu_PricesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string MenuFunctions_ProductMenu_Properties {
            get {
                return ResourceManager.GetString("MenuFunctions_ProductMenu_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string MenuFunctions_ProductMenu_Qty {
            get {
                return ResourceManager.GetString("MenuFunctions_ProductMenu_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove EAN.
        /// </summary>
        internal static string MenuFunctions_ProductMenu_Remove_EAN {
            get {
                return ResourceManager.GetString("MenuFunctions_ProductMenu_Remove_EAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Price.
        /// </summary>
        internal static string MenuFunctions_ProductMenu_Remove_Price {
            get {
                return ResourceManager.GetString("MenuFunctions_ProductMenu_Remove_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove record.
        /// </summary>
        internal static string MenuFunctions_ProductMenu_Remove_record {
            get {
                return ResourceManager.GetString("MenuFunctions_ProductMenu_Remove_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show EANs.
        /// </summary>
        internal static string MenuFunctions_ProductMenu_Show_EANs {
            get {
                return ResourceManager.GetString("MenuFunctions_ProductMenu_Show_EANs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show orders including item.
        /// </summary>
        internal static string MenuFunctions_ProductMenu_Show_orders_including_item {
            get {
                return ResourceManager.GetString("MenuFunctions_ProductMenu_Show_orders_including_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Prices.
        /// </summary>
        internal static string MenuFunctions_ProductMenu_Show_Prices {
            get {
                return ResourceManager.GetString("MenuFunctions_ProductMenu_Show_Prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU.
        /// </summary>
        internal static string MenuFunctions_ProductMenu_SKU {
            get {
                return ResourceManager.GetString("MenuFunctions_ProductMenu_SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Qty..
        /// </summary>
        internal static string MenuFunctions_ProductMenu_Stock {
            get {
                return ResourceManager.GetString("MenuFunctions_ProductMenu_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string MenuFunctions_ProductMenu_Unit {
            get {
                return ResourceManager.GetString("MenuFunctions_ProductMenu_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected EAN?.
        /// </summary>
        internal static string MenuFunctions_RemoveEAN_Are_you_sure_you_want_to_delete_the_selected_EAN_ {
            get {
                return ResourceManager.GetString("MenuFunctions_RemoveEAN_Are_you_sure_you_want_to_delete_the_selected_EAN_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected Order?.
        /// </summary>
        internal static string MenuFunctions_RemoveOrder_Click_Are_you_sure_you_want_to_delete_the_selected_Order_ {
            get {
                return ResourceManager.GetString("MenuFunctions_RemoveOrder_Click_Are_you_sure_you_want_to_delete_the_selected_Orde" +
                        "r_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string MenuFunctions_RemoveOrder_Click_Delete {
            get {
                return ResourceManager.GetString("MenuFunctions_RemoveOrder_Click_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order has already been shipped!.
        /// </summary>
        internal static string MenuFunctions_RemoveOrder_Click_Order_has_already_been_shipped_ {
            get {
                return ResourceManager.GetString("MenuFunctions_RemoveOrder_Click_Order_has_already_been_shipped_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected Partner?.
        /// </summary>
        internal static string MenuFunctions_RemovePartner_Click_Are_you_sure_you_want_to_delete_the_selected_Partner_ {
            get {
                return ResourceManager.GetString("MenuFunctions_RemovePartner_Click_Are_you_sure_you_want_to_delete_the_selected_Pa" +
                        "rtner_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected Price?.
        /// </summary>
        internal static string MenuFunctions_RemovePrice_Are_you_sure_you_want_to_delete_the_selected_Price_ {
            get {
                return ResourceManager.GetString("MenuFunctions_RemovePrice_Are_you_sure_you_want_to_delete_the_selected_Price_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected Record?.
        /// </summary>
        internal static string MenuFunctions_RemoveRecord_Are_you_sure_you_want_to_delete_the_selected_Record_ {
            get {
                return ResourceManager.GetString("MenuFunctions_RemoveRecord_Are_you_sure_you_want_to_delete_the_selected_Record_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string MenuFunctions_ShippedOrder_Click_Are_you_sure_ {
            get {
                return ResourceManager.GetString("MenuFunctions_ShippedOrder_Click_Are_you_sure_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order already shipped!.
        /// </summary>
        internal static string MenuFunctions_ShippedOrder_Click_Order_already_shipped_ {
            get {
                return ResourceManager.GetString("MenuFunctions_ShippedOrder_Click_Order_already_shipped_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped.
        /// </summary>
        internal static string MenuFunctions_ShippedOrder_Click_Shipped {
            get {
                return ResourceManager.GetString("MenuFunctions_ShippedOrder_Click_Shipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough stock for requested amount! Current stock: {0}.
        /// </summary>
        internal static string MenuFunctions_UpdateStock_Not_enough_stock_for_requested_amount__Current_stock___0_ {
            get {
                return ResourceManager.GetString("MenuFunctions_UpdateStock_Not_enough_stock_for_requested_amount__Current_stock___" +
                        "0_", resourceCulture);
            }
        }
    }
}
